/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingIndexRouteImport } from './routes/shopping/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as CooksIndexRouteImport } from './routes/cooks/index'
import { Route as SettingsHouseholdRouteImport } from './routes/settings/household'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'
import { Route as IngredientsNewRouteImport } from './routes/ingredients/new'
import { Route as CooksQueuedCookIdRouteImport } from './routes/cooks/$queuedCookId'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/recipes/$recipeId.index'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes/$recipeId.edit'
import { Route as RecipesRecipeIdCookRouteImport } from './routes/recipes/$recipeId.cook'
import { Route as IngredientsIngredientIdEditRouteImport } from './routes/ingredients/$ingredientId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingIndexRoute = ShoppingIndexRouteImport.update({
  id: '/shopping/',
  path: '/shopping/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const CooksIndexRoute = CooksIndexRouteImport.update({
  id: '/cooks/',
  path: '/cooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHouseholdRoute = SettingsHouseholdRouteImport.update({
  id: '/settings/household',
  path: '/settings/household',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CooksQueuedCookIdRoute = CooksQueuedCookIdRouteImport.update({
  id: '/cooks/$queuedCookId',
  path: '/cooks/$queuedCookId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRecipeIdRoute,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RecipesRecipeIdRoute,
} as any)
const RecipesRecipeIdCookRoute = RecipesRecipeIdCookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => RecipesRecipeIdRoute,
} as any)
const IngredientsIngredientIdEditRoute =
  IngredientsIngredientIdEditRouteImport.update({
    id: '/ingredients/$ingredientId/edit',
    path: '/ingredients/$ingredientId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cooks/$queuedCookId': typeof CooksQueuedCookIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/cooks/': typeof CooksIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cooks/$queuedCookId': typeof CooksQueuedCookIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/cooks': typeof CooksIndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/shopping': typeof ShoppingIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cooks/$queuedCookId': typeof CooksQueuedCookIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/cooks/': typeof CooksIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
  '/recipes/$recipeId/cook': typeof RecipesRecipeIdCookRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/cooks/$queuedCookId'
    | '/ingredients/new'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/settings/household'
    | '/cooks/'
    | '/ingredients/'
    | '/recipes/'
    | '/shopping/'
    | '/ingredients/$ingredientId/edit'
    | '/recipes/$recipeId/cook'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/cooks/$queuedCookId'
    | '/ingredients/new'
    | '/recipes/new'
    | '/settings/household'
    | '/cooks'
    | '/ingredients'
    | '/recipes'
    | '/shopping'
    | '/ingredients/$ingredientId/edit'
    | '/recipes/$recipeId/cook'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/cooks/$queuedCookId'
    | '/ingredients/new'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/settings/household'
    | '/cooks/'
    | '/ingredients/'
    | '/recipes/'
    | '/shopping/'
    | '/ingredients/$ingredientId/edit'
    | '/recipes/$recipeId/cook'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CooksQueuedCookIdRoute: typeof CooksQueuedCookIdRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRouteWithChildren
  RecipesNewRoute: typeof RecipesNewRoute
  SettingsHouseholdRoute: typeof SettingsHouseholdRoute
  CooksIndexRoute: typeof CooksIndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ShoppingIndexRoute: typeof ShoppingIndexRoute
  IngredientsIngredientIdEditRoute: typeof IngredientsIngredientIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/': {
      id: '/shopping/'
      path: '/shopping'
      fullPath: '/shopping/'
      preLoaderRoute: typeof ShoppingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooks/': {
      id: '/cooks/'
      path: '/cooks'
      fullPath: '/cooks/'
      preLoaderRoute: typeof CooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/household': {
      id: '/settings/household'
      path: '/settings/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof SettingsHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooks/$queuedCookId': {
      id: '/cooks/$queuedCookId'
      path: '/cooks/$queuedCookId'
      fullPath: '/cooks/$queuedCookId'
      preLoaderRoute: typeof CooksQueuedCookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/': {
      id: '/recipes/$recipeId/'
      path: '/'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof RecipesRecipeIdRoute
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof RecipesRecipeIdRoute
    }
    '/recipes/$recipeId/cook': {
      id: '/recipes/$recipeId/cook'
      path: '/cook'
      fullPath: '/recipes/$recipeId/cook'
      preLoaderRoute: typeof RecipesRecipeIdCookRouteImport
      parentRoute: typeof RecipesRecipeIdRoute
    }
    '/ingredients/$ingredientId/edit': {
      id: '/ingredients/$ingredientId/edit'
      path: '/ingredients/$ingredientId/edit'
      fullPath: '/ingredients/$ingredientId/edit'
      preLoaderRoute: typeof IngredientsIngredientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecipesRecipeIdRouteChildren {
  RecipesRecipeIdCookRoute: typeof RecipesRecipeIdCookRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
}

const RecipesRecipeIdRouteChildren: RecipesRecipeIdRouteChildren = {
  RecipesRecipeIdCookRoute: RecipesRecipeIdCookRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
}

const RecipesRecipeIdRouteWithChildren = RecipesRecipeIdRoute._addFileChildren(
  RecipesRecipeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CooksQueuedCookIdRoute: CooksQueuedCookIdRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRouteWithChildren,
  RecipesNewRoute: RecipesNewRoute,
  SettingsHouseholdRoute: SettingsHouseholdRoute,
  CooksIndexRoute: CooksIndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ShoppingIndexRoute: ShoppingIndexRoute,
  IngredientsIngredientIdEditRoute: IngredientsIngredientIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
