/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as SettingsHouseholdRouteImport } from './routes/settings/household'
import { Route as IngredientsNewRouteImport } from './routes/ingredients/new'
import { Route as IngredientsIngredientIdEditRouteImport } from './routes/ingredients/$ingredientId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHouseholdRoute = SettingsHouseholdRouteImport.update({
  id: '/settings/household',
  path: '/settings/household',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientIdEditRoute =
  IngredientsIngredientIdEditRouteImport.update({
    id: '/ingredients/$ingredientId/edit',
    path: '/ingredients/$ingredientId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/ingredients/$ingredientId/edit': typeof IngredientsIngredientIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/ingredients/new'
    | '/settings/household'
    | '/ingredients/'
    | '/ingredients/$ingredientId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/ingredients/new'
    | '/settings/household'
    | '/ingredients'
    | '/ingredients/$ingredientId/edit'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/ingredients/new'
    | '/settings/household'
    | '/ingredients/'
    | '/ingredients/$ingredientId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  SettingsHouseholdRoute: typeof SettingsHouseholdRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  IngredientsIngredientIdEditRoute: typeof IngredientsIngredientIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/household': {
      id: '/settings/household'
      path: '/settings/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof SettingsHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientId/edit': {
      id: '/ingredients/$ingredientId/edit'
      path: '/ingredients/$ingredientId/edit'
      fullPath: '/ingredients/$ingredientId/edit'
      preLoaderRoute: typeof IngredientsIngredientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  SettingsHouseholdRoute: SettingsHouseholdRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  IngredientsIngredientIdEditRoute: IngredientsIngredientIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
